### ISSUE TITLE
Japanese "backslash" in the demo

### ISSUE THREAD

**Issue by mgaunard** [akabe/evilml#1]
Whenever I type a backslash (\) in the demo, I get a japanese character instead. Copy-pasting the text into another editor gives me a normal backslash.
This must be tied to the font or some other setting related to text rendering.

Would it be possible to make that an option?

**Comment by akabe** [comment]
I cannot reproduce your problem, and a font family used in the demo is only monospace. I changed the lang attribute of html tag from "ja" to "en". Cannot you input a backslash still?

**Comment by mgaunard** [comment]
It now works correctly.
Wouldn't it be better to not specify that attribute at all though, and let the browser do the right thing based on locale settings or some such?

**Comment by akabe** [comment]
That's true. I removed the attribute. Thanks.
